### ISSUE TITLE
Thin White Round Border on the corners of the certain window (GNOME 45.0)

### ISSUE THREAD

**Issue by masterdokuro** [vinceliuice/Orchis-theme#387]
On ubuntu 23.10 with GNOME 45.0 and I've noticed a thin white round border on the corners of the certain window (see screenshot below). Below are the commands I use to install the theme.

./install.sh --theme default --color standard --libadwaita
./install.sh --tweaks submenu compact --shell 44

![Screenshot from 2023-11-08 08-03-58](https://github.com/vinceliuice/Orchis-theme/assets/148326796/07f17c8a-c8ee-440b-ae9d-670032fe746a)

This can be a little hard to see if you don't have a dark background wallpaper behind the open window. I've used Filezilla in this example but there are many applications this happens with and others don't show this, image viewer for example in the screenshot below.

![Screenshot from 2023-11-08 08-08-40](https://github.com/vinceliuice/Orchis-theme/assets/148326796/a56d3f1e-c1d7-4552-b068-bd30d3017f67)

This is rather a small bug but if its easy enough to fix then that would be great.  BTW, I never noticed this on the ubuntu 22.04.

**Comment by simon50keda** [comment]
It's funny enough that this does not happen if one is using Orchis-Dark or dark style Orchis theme.

**Comment by masterdokuro** [comment]
Your right.  Does not happen when **--color dark** is used.  Guess its a bug with **--color standard**.  Still, while minor I do hope someday this will be fixed.

Also, changing --round 15px makes it more noticeable in case that is of help to fixing the issue.

**Comment by vinceliuice** [comment]
There is a issue with gnome's theme engine. The gnome team adds a mask to the background in order to achieve rounded corners at the bottom. This results in the elements above not being able to completely cover the background color. The rounded corners will still show a bit of the background color of the window. The dark and light versions are fine. That’s because the color of the headerbar is consistent with the window, so there’s no problem.

**Comment by masterdokuro** [comment]
Okay, thank you for the investigation and explanation.  I'll close this issue with those comments.
