### ISSUE TITLE
Theme applied to legacy applications causes issues when window focused

### ISSUE THREAD

**Issue by austin-kallungal** [vinceliuice/Orchis-theme#491]
![Screenshot From 2024-12-21 23-56-17](https://github.com/user-attachments/assets/a8edf689-e7c1-4490-a682-d60a71c3241d)
![Screenshot From 2024-12-21 23-58-26](https://github.com/user-attachments/assets/d1249aa8-cb9b-4566-a281-d318d96932d4)

**Comment by ASKaraferias** [comment]
Did you solve this? I have the same issue.

**Comment by auspisses** [comment]
@ASKaraferias I can't remember what specifically fixed it, but this is the command line I use to install my theme
```
./install.sh -t grey -c dark --tweaks solid compact black primary submenu dock -l
sudo flatpak override --filesystem=xdg-config/gtk-3.0 && sudo flatpak override --filesystem=xdg-config/gtk-4.0
```
My guess would be fully uninstalling and reinstalling the theme would help you figure out if the problem lies within the theme or your system. If I remember what fixed it for me, I'll let you know. Good luck!

**Comment by ASKaraferias** [comment]
Thank you. I solved it differently, so I'm just going to write it here if anyone is looking.
I installed all the themes in ~/.local/share/themes/ and I copied the gtk-3.0 folder in my $XDG_CONFIG_HOME/ . Then I **also** selected the same theme from Gnome Tweaks, that way it set the settings.ini file correctly.
